version: "3.6"

networks:
  vinalsNetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/16
   

services:
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}/docker/portainer/data:/data
      - ${USERDIR}/docker/shared:/shared
    environment:
      - TZ=${TZ}
    networks:
      vinalsNetwork:
        ipv4_address: 172.20.0.27

  radarr:
    image: "linuxserver/radarr:latest"
    container_name: "radarr"
    volumes:
      - ${USERDIR}/docker/radarr:/config
      - ${USERDIR}/Downloads/completed:/downloads
      - ${USERDIR}/media/movies:/movies
      - /mnt/2TB_Samsung/Peliculas:/moviesSamsung2Tb
      - /mnt/1TB_Samsung/Peliculas:/moviesSamsung1Tb
      - /mnt/SSD2tb/Pelis:/moviesSSD2Tb
      - "/etc/localtime:/etc/localtime:ro"
      - ${USERDIR}/docker/shared:/shared
    ports:
      - "7878:7878"
    restart: always
    networks:
      vinalsNetwork:
        ipv4_address: 172.20.0.16
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  sonarr:
    image: "linuxserver/sonarr:latest"
    container_name: "sonarr"
    volumes:
      - ${USERDIR}/docker/sonarr:/config
      - ${USERDIR}/Downloads/completed:/downloads
      - ${USERDIR}/media/tvshows:/tv
      - /mnt/2TB_Samsung/SeriesTV:/TvSamsung2Tb
      - /mnt/1TB_Samsung/SeriesTV:/TvSamsung1Tb
      - /mnt/SSD2tb/Series:/TvSSD2Tb
      - "/etc/localtime:/etc/localtime:ro"
      - ${USERDIR}/docker/shared:/shared
    ports:
        - "8989:8989"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      vinalsNetwork:
        ipv4_address: 172.20.0.6
  
  jackett:
    image: "linuxserver/jackett"
    container_name: "jackett"
    volumes:
      - ${USERDIR}/docker/jackett:/config
      - ${USERDIR}/Downloads/completed:/downloads
      - "/etc/localtime:/etc/localtime:ro"
      - ${USERDIR}/docker/shared:/shared
    ports:
      - "9117:9117"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      vinalsNetwork:
        ipv4_address: 172.20.0.5
  
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/docker/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped
    networks:
      vinalsNetwork:
        ipv4_address: 172.20.0.8

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    #network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM= #optional
    ports:
      - "32400:32400"
    volumes:
      - ${USERDIR}/docker/plex:/config
      - ${USERDIR}/media/tvshows:/tv
      - ${USERDIR}/media/movies:/movies
      - /mnt/2TB_Samsung/Peliculas:/Disco2TB/peliculas
      - /mnt/2TB_Samsung/SeriesTV:/Disco2TB/series
      - /mnt/1TB_Samsung/Peliculas:/Disco1TB/peliculas
      - /mnt/1TB_Samsung/SeriesTV:/Disco1TB/series
      - /mnt/SSD2tb/Pelis:/Disco_2tb/peliculas
      - /mnt/SSD2tb/Series:/Disco_2tb/series
    restart: unless-stopped
    networks:
      vinalsNetwork:
        ipv4_address: 172.20.0.7
    

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.0
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=4444
    volumes:
      - ${USERDIR}/docker/qbittorrent:/config
      - ${USERDIR}/Downloads/completed:/downloads
    ports:
      - 4444:4444
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      vinalsNetwork:
        ipv4_address: 172.20.0.12


  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ${USERDIR}/docker/traefik:/etc/traefik
    restart:
      always
    networks:
      vinalsNetwork:
        ipv4_address: 172.20.0.3
    

  clouflared:
    image: cloudflare/cloudflared:2022.2.2
    container_name: clouflared
    command: tunnel run ${CLOUDFLARE_TUNNEL}
    networks:
      vinalsNetwork:
        ipv4_address: 172.20.0.2
    volumes:
      - ${USERDIR}/docker/cloudflared:/home/nonroot/.cloudflared
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  guacd:
    container_name: guacamole_guacd
    image: guacamole/guacd
    hostname: guacd
    networks:
      vinalsNetwork:
        ipv4_address: 172.20.0.10
    ports:
      - 4822:4822 # HTTP port
    volumes:
      - ${USERDIR}/docker/guacad/data:/data # Configuration directory
    restart: always

  guacamole:
    container_name: guacamole
    image: guacamole/guacamole
    depends_on:
      - guacd
      - mariadb
    links:
      - guacd
      - mariadb
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: mariadb
      MYSQL_DATABASE: guacamole
      MYSQL_USER: guacamole
      MYSQL_PASSWORD: 25061992A
    networks:
      vinalsNetwork:
        ipv4_address: 172.20.0.15
    ports:
      - 4457:8080/tcp
    volumes:
      - ${USERDIR}/docker/guacamole/data:/data # Configuration directory
    restart: always

  mariadb:
    image: "linuxserver/mariadb"
    container_name: "mariadb"
    hostname: mariadb
    volumes:
      - ${USERDIR}/docker/mariadb:/config
    networks:
      vinalsNetwork:
        ipv4_address: 172.20.0.25
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host 
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=27101998
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  phpmyadmin:
    hostname: phpmyadmin
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mariadb:db
    networks:
      vinalsNetwork:
        ipv4_address: 172.20.0.11
    ports:
      - "4442:80"
    environment:
      - PMA_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=27101998
  
  dbeaver:
    image: dbeaver/cloudbeaver:21.1.1
    container_name: dbeaver
    ports:
      - "8085:8978"
    environment:
      - CB_ADMIN_NAME=admin
      - CB_ADMIN_PASSWORD=admin
    volumes:
      - dbeaver-data:/opt/cloudbeaver/workspace
    networks:
      vinalsNetwork:
        ipv4_address: 172.20.0.37
    

  tfg-backend:
    container_name: tfg-backend
    image: tfg-backend
    build:
      context: ./api-tfg
      target: development
    ports:
      - 3000:3000
    networks:
      vinalsNetwork:
        ipv4_address: 172.20.0.33
    restart: always


  nginx:
    image: nginx:latest
    container_name: web
    ports:
      - 8088:80
    volumes:
      - ./htmlPrivacidad/:/usr/share/nginx/html:ro
    networks:
      vinalsNetwork:
        ipv4_address: 172.20.0.34
    restart: always

  nginx2:
    image: nginx:latest
    container_name: soporte
    ports:
      - 8087:80
    volumes:
      - ./htmlSoporte/:/usr/share/nginx/html:ro
    networks:
      vinalsNetwork:
        ipv4_address: 172.20.0.35
    restart: always

  

  prowlarr:
    image: "hotio/prowlarr:testing"
    container_name: prowlarr
    networks:
      vinalsNetwork:
        ipv4_address: 172.20.0.9
    ports:
      - "4446:9696"
    volumes:
      - ${USERDIR}/docker/prowlarr:/config
    restart: always


volumes:
  dbeaver-data:

