-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgeGpcZ0kNokFijOZ/
uBhS28nemKeDA4kScmOEKInAKUOgCgYIKoZIzj0DAQehRANCAAQChbHNzuMKbGAT
kogcFq5W+L74iIXcuvVMPQkLDPlPvIxSF9w6H+hqGTw8j0up6MO6iT/sqUtINYG5
whCM9E+7
-----END PRIVATE KEY-----