tunnel: 0ad946ba-97e8-4a80-8a11-4f2f0b7852c5
credentials-file: /home/nonroot/.cloudflared/0ad946ba-97e8-4a80-8a11-4f2f0b7852c5.json

# NOTE: You should only have one ingress tag, so if you uncomment one block comment the others

# forward all traffic to Reverse Proxy w/ SSL
ingress:
  - service: https://traefik:443
    originRequest:
      noTLSVerify: true
      originServerName: lapspartbox.com

#forward all traffic to Reverse Proxy w/ SSL and no TLS Verify
#ingress:
#  - service: https://REVERSEPROXYIP:PORT
#    originRequest:
#      noTLSVerify: true

# forward all traffic to reverse proxy over http
#ingress:
#  - service: http://REVERSEPROXYIP:PORT